label_mappings:
  - labels: 
      - hold
    comment: Wait, please do not proceed this yet.
  - labels: 
      - lang/en
    comment: To see where this is in the review pipeline and follow the progress, please have a look at the [project board](https://github.com/orgs/cncf/projects/26/views/1).
