# cSpell:ignore pagefind regexs
DirectoryPath: public
# IgnoreDirectoryMissingTrailingSlash: true # FIXME
IgnoreInternalEmptyHash: true # FIXME
IgnoreDirs:
  - ^(bn|de|hi|it|ko|pt.*?|ru|tr|ur|zh.*?)/
IgnoreURLs: # list of regexs of paths or URLs to be ignored
  - ^/pagefind
