name: Request to add a new term (English)
description: Issue to add a new term in English
title: "[New term] `GlossaryTermHere`"
labels: ["lang/en","new term","triage/awaiting"]
body:
  - type: markdown
    attributes:
      value: |
        ---
        ## Thanks for taking the time to add a request to the glossary!
        
        This issue-template is to propose a new Glossary term.
        Please check https://glossary.cncf.io/contribute/#propose-new-terms first.

  - type: textarea
    id: details
    attributes:
      label: 1. Please describe why this term needs to be added
      value: |
        #### What this term is about? (briefly)
        - 
        #### Why this term needs to be added? (briefly) 
        - 
    validations:
      required: true
  - type: checkboxes
    id: checkboxes
    attributes:
      label: 2. Checklist
      options:
        - label: The suggested term fits the [cloud native definition](https://github.com/cncf/toc/blob/main/DEFINITION.md) or is essential to understanding cloud native terms. (We hope to avoid adding general or broad terminologies)
          required: true
        - label: There is no existing issue yet. [(shift+click to check existing issues)](https://github.com/cncf/glossary/issues?q=label%3A%22new+term%22)
          required: true
        - label: The term has not already been declined in the past. [(shift+click to check)](https://github.com/cncf/glossary/issues?q=is%3Aissue+is%3Aclosed+label%3A%22triage%2Fnot+accepted%22)
          required: false
        - label: The term does not already exist in the [glossary](https://glossary.cncf.io) as a completed term, nor does it exist in [this directory](https://github.com/cncf/glossary/tree/main/content/en) as an incomplete term. (If the status of the term is `Feedback Appreciated`, consider updating the term.)
          required: true
        - label: I understand that maintainers will assess if the term should be part of the Glossary. (Please be patient)
          required: true
        - label: I want to work on this term and confirm that I meet the criteria as outlined in "[who can contribute](https://glossary.cncf.io/contribute/#who-can-contribute)". (If not checked, maintainers will assign another volunteer)
          required: false
  - type: textarea
    id: note
    attributes:
      label: (Note)
      value: |
        Maintainers will assign a label after assessment procedure. 
        (from `triage/awaiting` to `triage/accepted` or `triage/not accepted`)

        A contributor can be assigned to this issue after the issue get the `triage/accepted` label.
        The assignee needs to check [Style Guide](https://glossary.cncf.io/style-guide/).
