name: Portuguese Language Glossary Request
description: Portuguese Language Glossary Request Definition
title: "[portuguese]: GlossaryWordHere"
labels: ["portuguese"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to add a request to the glossary!
  - type: textarea
    id: details
    attributes:
      label: Details (optional)
      description: Please feel free to add any additional details here
      placeholder: Tell us what you see!
      value: "Optional details"
    validations:
      required: false
