---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2022
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

matrix:
  - name: Spanish content
    sources:
      - 'content/es/**/*.md'
    default_encoding: utf-8
    aspell:
      lang: es
      ignore-case: true
    dictionary:
      wordlists:
        - content/es/.wordlist.txt
      output: /tmp/aspell.dic
      encoding: utf-8
    pipeline:
      - pyspelling.filters.markdown:
      - pyspelling.filters.html:
          comments: false
          ignores:
            - code
            - pre
